// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: frr.proto

package frr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Greetings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *Greetings) Reset() {
	*x = Greetings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greetings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greetings) ProtoMessage() {}

func (x *Greetings) ProtoReflect() protoreflect.Message {
	mi := &file_frr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greetings.ProtoReflect.Descriptor instead.
func (*Greetings) Descriptor() ([]byte, []int) {
	return file_frr_proto_rawDescGZIP(), []int{0}
}

func (x *Greetings) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_frr_proto protoreflect.FileDescriptor

var file_frr_proto_rawDesc = []byte{
	0x0a, 0x09, 0x66, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x66, 0x72, 0x72,
	0x22, 0x27, 0x0a, 0x09, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f,
	0x2e, 0x2e, 0x2f, 0x66, 0x72, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frr_proto_rawDescOnce sync.Once
	file_frr_proto_rawDescData = file_frr_proto_rawDesc
)

func file_frr_proto_rawDescGZIP() []byte {
	file_frr_proto_rawDescOnce.Do(func() {
		file_frr_proto_rawDescData = protoimpl.X.CompressGZIP(file_frr_proto_rawDescData)
	})
	return file_frr_proto_rawDescData
}

var file_frr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frr_proto_goTypes = []interface{}{
	(*Greetings)(nil), // 0: frr.Greetings
}
var file_frr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frr_proto_init() }
func file_frr_proto_init() {
	if File_frr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greetings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frr_proto_goTypes,
		DependencyIndexes: file_frr_proto_depIdxs,
		MessageInfos:      file_frr_proto_msgTypes,
	}.Build()
	File_frr_proto = out.File
	file_frr_proto_rawDesc = nil
	file_frr_proto_goTypes = nil
	file_frr_proto_depIdxs = nil
}
